version: "3.3"

services:
  # contenedor para desarrollo
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: dev_container
    volumes:
      - ../datos:/workdir/datos
      - ../codigo:/workdir/codigo
      - /tmp/.X11-unix:/tmp/.X11-unix # para generar ventana de graficos (matplotlib, opencv, etc.)
    ports:
      - 8889:8888